**WORKING WITH TEAMS DATASET TO PREDICT THE WINNER GIVEN TWO TEAMS**

In [15]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.cluster import KMeans
import pandas as pd
import numpy as np
import io
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
from numpy import mean
from numpy import std
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression

In [3]:
from google.colab import files
uploaded = files.upload()
teams = pd.read_csv(io.StringIO(uploaded['team_season.csv'].decode('utf-8')),sep=';')
teams.head()

Saving team_season.csv to team_season.csv


team  year leag  o_fgm  o_fga  o_ftm  ...  d_3pm  d_3pa  d_pts  pace  won  lost
0  BOS  1946    N   1397   5133    811  ...      0      0   3900   0.0   22    38
1  CH1  1946    N   1879   6309    939  ...      0      0   4471   0.0   39    22
2  CL1  1946    N   1674   5699    903  ...      0      0   4308   0.0   30    30
3  DE1  1946    N   1437   5843    923  ...      0      0   3918   0.0   20    40
4  NYK  1946    N   1465   5255    951  ...      0      0   3840   0.0   33    27

[5 rows x 36 columns]

In [5]:
teams =teams.drop(['o_oreb',	'o_dreb',	'o_reb','pace','o_stl',	'o_to',	'o_blk',	'o_3pm',	'o_3pa','d_fgm',	'd_fga',	'd_ftm',	'd_fta',	'd_oreb',	'd_dreb',	'd_reb',	'd_asts',	'd_pf',	'd_stl',	'd_to',	'd_blk',	'd_3pm',	'd_3pa'],axis=1)

In [6]:
teams.mean()

year      1980.983151
o_fgm     3178.642797
o_fga     7037.718618
o_ftm     1716.262005
o_fta     2300.532435
o_asts    1838.155855
o_pf      1913.334457
o_pts     8234.272957
d_pts     8234.548441
won         39.650379
lost        39.650379
dtype: float64

**CALCULATING THE WINNING RATE OF THE TEAM AND CLASSIFYING TEAMS AS OUTSTANDING OR NOT**

In [7]:
teams['WinRate'] = teams['won']/60

In [8]:
teams.head()

team  year leag  o_fgm  o_fga  o_ftm  ...  o_pf  o_pts  d_pts  won  lost   WinRate
0  BOS  1946    N   1397   5133    811  ...  1202   3605   3900   22    38  0.366667
1  CH1  1946    N   1879   6309    939  ...  1473   4697   4471   39    22  0.650000
2  CL1  1946    N   1674   5699    903  ...  1246   4251   4308   30    30  0.500000
3  DE1  1946    N   1437   5843    923  ...  1351   3797   3918   20    40  0.333333
4  NYK  1946    N   1465   5255    951  ...  1218   3881   3840   33    27  0.550000

[5 rows x 14 columns]

In [9]:
teams["lost"].mean()

39.65037910699242

In [10]:
teams["outstanding"] = (teams["WinRate"]>0.5)

In [12]:
teams.head([win])

team  year leag  o_fgm  o_fga  ...  d_pts  won  lost   WinRate  outstanding
0  BOS  1946    N   1397   5133  ...   3900   22    38  0.366667        False
1  CH1  1946    N   1879   6309  ...   4471   39    22  0.650000         True
2  CL1  1946    N   1674   5699  ...   4308   30    30  0.500000        False
3  DE1  1946    N   1437   5843  ...   3918   20    40  0.333333        False
4  NYK  1946    N   1465   5255  ...   3840   33    27  0.550000         True

[5 rows x 15 columns]

In [13]:
teams['outstanding']=teams['outstanding'].astype(int)

In [14]:
teams.head()

team  year leag  o_fgm  o_fga  ...  d_pts  won  lost   WinRate  outstanding
0  BOS  1946    N   1397   5133  ...   3900   22    38  0.366667            0
1  CH1  1946    N   1879   6309  ...   4471   39    22  0.650000            1
2  CL1  1946    N   1674   5699  ...   4308   30    30  0.500000            0
3  DE1  1946    N   1437   5843  ...   3918   20    40  0.333333            0
4  NYK  1946    N   1465   5255  ...   3840   33    27  0.550000            1

[5 rows x 15 columns]

In [69]:
X = teams.drop(['outstanding','team','year','leag'],axis=1)

In [30]:
X = teams.drop(['outstanding'],axis=1)

In [31]:
Y = teams['outstanding']

In [36]:
X_train , X_test, Y_train, Y_test = train_test_split(X, Y, random_state=0)

**AdaBoost Classifier**

In [76]:
teams_classifier = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=5),
    n_estimators=50, learning_rate=0.5
)
teams_classifier.fit(X_train, Y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=5,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort='deprecated',
                          

In [77]:
prediction = teams_classifier.predict(X_test)

In [78]:
confusion_matrix(Y_test,prediction)

array([[ 77,   0],
       [  0, 220]])

In [64]:
teams_classifier.score(X_test,Y_test)

1.0

**Logistic Regression**

In [51]:
logistic_model = Supp
logistic_model.fit(X_train,Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [81]:
prediction_logic = logistic_model.predict(X_test)

In [82]:
confusion_matrix(Y_test,prediction_logic)

array([[ 77,   0],
       [  0, 220]])

In [83]:
logistic_model.score(X_test,Y_test)

1.0

**Support Vector Machine**

In [57]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [66]:
prediction_svc = svclassifier.predict(X_test)

In [67]:
confusion_matrix(Y_test,prediction_svc)

array([[ 74,   3],
       [  1, 219]])

In [68]:
svclassifier.score(X_test,Y_test)

0.9865319865319865

**Method That Predicts The winner Between Two Teams Using SVC**

In [117]:
def predict_winner(team1,team2):
  team1_nums = team1.drop(['team','year','leag','outstanding'],axis=1)
  team2_nums = team2.drop(['team','year','leag','outstanding'],axis=1)

  out_team1 = svclassifier.predict(team1_nums)
  out_team2 = svclassifier.predict(team2_nums)

  if out_team1>out_team2:
    return [1,0,0]
  elif out_team2>out_team1:
    return [0,0,1]
  elif team1['WinRate']>team2['WinRate']:
    return [1,0,0]
  elif team2['WinRate']>team1['WinRate']:
    return [0,0,1]
  else: return [0,1,0]



In [110]:
team_year = teams.loc[teams['year']==1946] #James = numeric_columns.loc[players['firstname']=="LeBron"]

In [112]:
tm1 = team_year.loc[team_year['team']=="BOS"]
tm2 = team_year.loc[team_year['team']=="CH1"]

In [113]:
print(tm1)
print(tm2)

  team  year leag  o_fgm  o_fga  ...  d_pts  won  lost   WinRate  outstanding
0  BOS  1946    N   1397   5133  ...   3900   22    38  0.366667            0

[1 rows x 15 columns]
  team  year leag  o_fgm  o_fga  ...  d_pts  won  lost  WinRate  outstanding
1  CH1  1946    N   1879   6309  ...   4471   39    22     0.65            1

[1 rows x 15 columns]


In [118]:
pred = predict_winner(tm1,tm2)

In [119]:
pred

[0, 0, 1]